###
POST http://localhost:3000/api/event
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODcxOTY5MCwiZXhwIjoxNjM4ODA2MDkwfQ.r9p9bRtaJ-eUALlpo6oLfhqbFNbHVnYfjTZdkkZTiW0

{
   "name": "event 3",
   "description": "holding for what"
}

###
GET http://localhost:3000/api/event
content-type: application/json

###
GET http://localhost:3000/api/event/61ace31e6edce103e36bbcbe
content-type: application/json

###
POST http://localhost:3000/api/event/61ace31e6edce103e36bbcbe/join-event
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODcxOTY5MCwiZXhwIjoxNjM4ODA2MDkwfQ.r9p9bRtaJ-eUALlpo6oLfhqbFNbHVnYfjTZdkkZTiW0

###
POST http://localhost:3000/api/event/61ace31e6edce103e36bbcbe/leave-event
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODcxOTY5MCwiZXhwIjoxNjM4ODA2MDkwfQ.r9p9bRtaJ-eUALlpo6oLfhqbFNbHVnYfjTZdkkZTiW0
