###
POST http://localhost:3001/api/event
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFjNmNmMjA1MzI0MzgxOGMyNmIyMWYyIn0sImlhdCI6MTY0MDQ4MzAwMiwiZXhwIjoxNjQwNTY5NDAyfQ.4ZFFspyphAp4EkddW4PGmSnIcSgh3Zz0qfuDFqi8EP8

{
   "name": "event 4",
   "description": "some text here",
   "expiredDay": "3/2/2021"
}

###
GET http://localhost:3000/api/event
content-type: application/json

###
GET http://localhost:3000/api/event/61ace31e6edce103e36bbcbe
content-type: application/json

###
POST http://localhost:3000/api/event/61ace31e6edce103e36bbcbe/join-event
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODcxOTY5MCwiZXhwIjoxNjM4ODA2MDkwfQ.r9p9bRtaJ-eUALlpo6oLfhqbFNbHVnYfjTZdkkZTiW0

###
POST http://localhost:3000/api/event/61ace31e6edce103e36bbcbe/leave-event
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODcxOTY5MCwiZXhwIjoxNjM4ODA2MDkwfQ.r9p9bRtaJ-eUALlpo6oLfhqbFNbHVnYfjTZdkkZTiW0
