###
POST http://localhost:3000/api/post/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODYwMjkwMSwiZXhwIjoxNjM4Njg5MzAxfQ.dp897GCIaxXXgY6jsLV1O0fJRZyMZ1eqdPa9SrwJi3Q


{
  "postTitle": "post test 1",
  "postContent": "so 1",
  "topicId": "61aa3990bbd0cecf1bf1799c"
}

###
GET http://localhost:3000/api/post/
content-type: application/json

###
GET http://localhost:3000/api/post/61ac5b5635075a9debb55549
content-type: application/json


###
DELETE http://localhost:3000/api/post/619f947fce79a5bff9a8dde6
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODYwMjkwMSwiZXhwIjoxNjM4Njg5MzAxfQ.dp897GCIaxXXgY6jsLV1O0fJRZyMZ1eqdPa9SrwJi3Q


###
PUT http://localhost:3000/api/post/61ac5b5635075a9debb55549
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODYwMjkwMSwiZXhwIjoxNjM4Njg5MzAxfQ.dp897GCIaxXXgY6jsLV1O0fJRZyMZ1eqdPa9SrwJi3Q

{
  "updatedPost": {
    "postContent": "so 2"
  }
}

###
POST http://localhost:3000/api/post/61ac5b5635075a9debb55549/vote-up
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODY5MTUxNSwiZXhwIjoxNjM4Nzc3OTE1fQ.B0-jLZ3MMZnBgk-glTgecaSb_aEjQgmftYZQz4-JBRg

###
POST http://localhost:3000/api/post/61ac5b5635075a9debb55549/vote-down
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODY5MTUxNSwiZXhwIjoxNjM4Nzc3OTE1fQ.B0-jLZ3MMZnBgk-glTgecaSb_aEjQgmftYZQz4-JBRg

###
POST http://localhost:3000/api/post/61ac5b5635075a9debb55549/comment
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODY5MTUxNSwiZXhwIjoxNjM4Nzc3OTE1fQ.B0-jLZ3MMZnBgk-glTgecaSb_aEjQgmftYZQz4-JBRg

{
  "comment": "Hello first comment"
}