###
POST http://localhost:3001/api/auth/signin
content-type: application/json

{
    "studentId": "88888888888",
    "password": "123123123"
}

###
get http://localhost:3001/api/auth/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODQ2MDc1MSwiZXhwIjoxNjM4NTQ3MTUxfQ.D1DAedWGqBy001TTp24qBcVYBRLRm_4M5E3DqNuTrmw

###
POST http://localhost:3001/api/auth/create-user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODQ0Njc1MywiZXhwIjoxNjM4NTMzMTUzfQ.EGQNXoxwnE8dqdbwLNcIPKqlzjO8W0FSRJfFIjKVoUE

{
    "email":"a4@gmail.com",
    "studentId": "44444444444",
    "name": "truong4",
    "password": "12345",
    "role": "student",
    "course": "k24",
    "faculty": "IT"
}
###
POST http://localhost:3001/api/auth/change-password
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODIwMzE1MiwiZXhwIjoxNjM4Mjg5NTUyfQ.YQeK9AA4qBwz0-E5v7bpiC5Fteodgsgfkk3vaxErTD4

{
    "newPassword": "123123123"
}

###
POST http://localhost:3001/api/auth/add-topic
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODQ2MDc1MSwiZXhwIjoxNjM4NTQ3MTUxfQ.D1DAedWGqBy001TTp24qBcVYBRLRm_4M5E3DqNuTrmw


{
    "topicId": "61a8ea23cfc6a554067a83b8"
}
###
POST http://localhost:3001/api/auth/remove-topic
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhMjM1OGE4Y2FlMmU1ODE0YTNlNTZjIn0sImlhdCI6MTYzODAyNDY1MCwiZXhwIjoxNjM4MTExMDUwfQ.ZIPhfpEKZ9w_cTu7wYn_OrgkWUUllxECw1-iCQQ89OU

{
    "topicId": "61a321a5de41df64d9756b7e"
}