###
POST http://localhost:3001/api/auth/signin
content-type: application/json

{
    "studentId": "24211206955",
    "password": "truong1508"
}

###
get http://localhost:3001/api/auth/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODQ2MDc1MSwiZXhwIjoxNjM4NTQ3MTUxfQ.D1DAedWGqBy001TTp24qBcVYBRLRm_4M5E3DqNuTrmw

###
POST http://localhost:3001/api/auth/create-user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODQ0Njc1MywiZXhwIjoxNjM4NTMzMTUzfQ.EGQNXoxwnE8dqdbwLNcIPKqlzjO8W0FSRJfFIjKVoUE

{
    "email":"admin@gmail.com",
    "studentId": "11111111111",
    "name": "admin",
    "password": "123123123",
    "role": "admin",
    "course": "k24",
    "faculty": "IT"
}
###
POST http://localhost:3001/api/auth/change-password
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODIwMzE1MiwiZXhwIjoxNjM4Mjg5NTUyfQ.YQeK9AA4qBwz0-E5v7bpiC5Fteodgsgfkk3vaxErTD4

{
    "newPassword": "123123123"
}

###
POST http://localhost:3001/api/auth/add-topic
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFhNGZlZjVmZDdmZmY4MzUxNDQ5ZGI3In0sImlhdCI6MTYzODQ2MDc1MSwiZXhwIjoxNjM4NTQ3MTUxfQ.D1DAedWGqBy001TTp24qBcVYBRLRm_4M5E3DqNuTrmw


{
    "topicId": "61a8ea23cfc6a554067a83b8"
}
